### ISSUE TITLE
Elección lenguaje programación

### ISSUE THREAD

**Issue by adelahera** [Enaraque/bus_stadistics#5]
El primer issue que se nos plantea para es la elección del lenguaje de programación apropiado para el problema a resolver. Yo creo que, por el estilo del problema que se plantea en las historias de usuario #3 y #4 , habría que usar un lenguaje fuertemente tipificado, para poder diferenciar bien los diferentes objetos valor y entidades. Por eso, te propongo dos opciones: utilizar Go o utilizar TypeScript. Creo que estas dos opciones son las que más se ajustan al problema, aunque si piensas que hay opciones mejores podemos hablarlo y ponernos de acuerdo.

**Comment by Enaraque** [comment]
Mi idea desde un principio era usar justamente go o typescript por lo que coincidimos en ambas opciones. Por mi parte, utilizaría `TypeScript` ya que desde hace un tiempo me llamó la atención aprenderlo y creo que ahora sería buen momento para ello.

**Comment by adelahera** [comment]
De acuerdo, coincidimos entonces. El lenguaje usado será TypeScript.
